[settings]
env_shell_expand = true

[env]
NERVES_WIFI_SSID = 'Wombat Festival'
NERVES_WIFI_PSK = 'orange-buffoon-2-prison'

[tools]
elixir = "latest"
erlang = "latest"
fwup = "latest"

[tasks.clean]
description = "delete all artifacts"
run = [
  "rimraf _build",
  "rimraf deps",
  "rimraf mix.lock",
  "rimraf .elixir_ls"
]

[tasks.tree]
description = "Show a tree of the project, without ignored folders"
run = "tree --gitignore"

[tasks.deps]
description = "Update dependencies"
env = { MIX_TARGET = { required = true }, MIX_ENV = { required = true } }
run = "mix deps.get"

[tasks.deps-all]
description = "Fetch Nerves dependencies for all targets"
shell = "fish -c"
run = """
set targets rpi5 rpi4 rpi3a rpi3 rpi0
for t in $targets
    echo "--- Target: $t ---"
    MIX_TARGET=$t mix deps.get
end
"""

[tasks.clean-compile]
env = { MIX_TARGET = { required = true }, MIX_ENV = { required = true } }
run = [
  "mix compile --force",
]
depends = ["clean", "deps"]

[tasks.build]
env = { MIX_TARGET = { required = true }, MIX_ENV = { required = true } }
description = "Build firmware"
run = "mix firmware"
raw = true

[tasks.upload]
description = "upload firmware to device"
env = { MIX_TARGET = { required = true }, MIX_ENV = { required = true } }
run = "mix upload BB-$MIX_TARGET.local"
raw = true

[tasks.dev]
description = "Run locally"
run = "iex -S mix"

[tasks.deploy]
depends = ["build"]
run = { task = "upload" }


# NOTE: Provisioning ONLY happens on a firmware BURN
[tasks.burn.env]
MIX_TARGET = { required = true }
MIX_ENV = { required = true }
NERVES_SERIAL_NUMBER="BB-{{env.MIX_TARGET | upper}}"

[tasks.burn]
description = "Burn firmware to sd card"
# Use a bash shell to ensure variable export works correctly
shell = "bash -c"
run = "sudo -E mix burn"


# [tasks."host:test"]
# description = "Run the project locally on your host"
# run = "iex -S mix test"
